version: '3'

services:
  component-api-gateway:
    build: .
    ports:
      - "7373:7373"
    environment:
      AUTHORIZATION_URL: http://localhost:4343
      AUTHENTICATION_URL: http://localhost:9393
      API_GATEWAY_URL: http://localhost:7373
