version: '3'

services:
  component-authentication:
    build: .
    expose:
      - 9393
    environment:
      DATABASE_USER: maat
      DATABASE_PASSWORD: SECURE&STRING_PASSWORD
      DATABASE_NAME: component_authentication_database
      DATABASE_HOSTNAME: 192.168.16.2
      DATABASE_PORT: 5432
    depends_on:
      database:
        condition: service_healthy
    networks:
      - db-link
      - default

  database:
    image: postgres:14-alpine
    restart: no
    user: postgres
    environment:
      POSTGRES_PASSWORD: 'SECURE&STRING_PASSWORD'
      POSTGRES_USER: 'maat'
      POSTGRES_DB: 'component_authentication_database'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
    networks:
      db-link:
        ipv4_address: 192.168.16.2

networks:
  db-link:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.16.1

volumes:
  pgdata:
